import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useQuery, useMutation } from '../convex/_generated/react'
import { useCallback } from 'react'
import React, { useState } from 'react';

const Admin: NextPage = () => {
  const setLocalized = useMutation('setLocalized');
  const [text, setText] = useState("");
  const [localizedText, setLocalizedText] = useState("");
  const [language, setLanguage] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js with Convex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Text: <input type="text" value={text} onChange={(e) => setText(e.target.value)} />
        Localized Text: <input type="text" value={localizedText} onChange={(e) => setLocalizedText(e.target.value)} />
        Language: <input type="text" value={language} onChange={(e) => setLanguage(e.target.value)} />
        <button className={styles.button} onClick={(e) => {
            setLocalized(text, localizedText, language);
            setText("");
            setLocalizedText("");
            setLanguage("");
        }}>
          Update Localization
        </button>
      </main>

    </div>
  )
}

export default Admin
